# Generated by Django 5.2.7 on 2025-11-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzeInvoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='anzahl_betroffener_suppliers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='severity_verteilung',
            field=models.JSONField(default=dict),
        ),
    ]
