# Generated by Django 5.2.7 on 2025-11-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzeInvoices', '0002_report_anzahl_betroffener_suppliers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='focus_node_verteilung',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='result_path_verteilung',
            field=models.JSONField(default=dict),
        ),
    ]
