# Generated by Django 5.2.7 on 2025-11-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzeInvoices', '0003_report_focus_node_verteilung_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='list_of_violations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='report',
            name='focus_node_verteilung',
            field=models.JSONField(default=dict),
        ),
    ]
