# Generated by Django 5.2.7 on 2025-11-14 12:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzeInvoices', '0004_report_list_of_violations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('filterID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('originalReportID', models.UUIDField()),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('violation_count', models.IntegerField(default=0)),
                ('anzahl_betroffener_suppliers', models.IntegerField(default=0)),
                ('focus_node_verteilung', models.JSONField(default=dict)),
                ('result_path_verteilung', models.JSONField(default=dict)),
                ('severity_verteilung', models.JSONField(default=dict)),
                ('list_of_violations', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='graph',
            field=models.TextField(default=''),
        ),
    ]
