# Generated by Django 5.2.7 on 2025-11-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzeInvoices', '0005_filter_report_graph'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='source_constraint_component_verteilung',
            field=models.JSONField(default=dict),
        ),
    ]
