# Generated by Django 5.2.8 on 2025-12-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzeInvoices', '0006_report_source_constraint_component_verteilung'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='source_constraint_component_verteilung',
            field=models.JSONField(default=dict),
        ),
    ]
