# Generated by Django 5.2.8 on 2025-12-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzeInvoices', '0007_filter_source_constraint_component_verteilung'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='datengraph',
            field=models.TextField(default=''),
        ),
    ]
