# Generated by Django 5.2.7 on 2025-12-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzeInvoices', '0008_report_datengraph'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='edi_content',
            field=models.TextField(default=''),
        ),
    ]
