# Generated by Django 5.2.8 on 2025-12-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzeInvoices', '0009_report_edi_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='allPaths',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='report',
            name='correlationData',
            field=models.JSONField(default=dict),
        ),
    ]
