# Generated by Django 5.2.8 on 2025-12-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzeInvoices', '0010_report_allpaths_report_correlationdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='correlationData',
            field=models.JSONField(default=list),
        ),
    ]
