# Generated by Django 5.2.8 on 2025-12-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzeInvoices', '0011_alter_report_correlationdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='anzahl_betroffener_shapes',
            field=models.IntegerField(default=0),
        ),
    ]
