# Generated by Django 5.2.8 on 2025-12-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzeInvoices', '0012_report_anzahl_betroffener_shapes'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='anteil_betroffener_shapes',
            field=models.FloatField(default=0.0),
        ),
    ]
