# Generated by Django 5.2.8 on 2025-12-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzeInvoices', '0013_report_anteil_betroffener_shapes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='anteil_betroffener_shapes',
            field=models.TextField(default='0%'),
        ),
    ]
