# Generated by Django 5.2.7 on 2026-01-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzeInvoices', '0014_alter_report_anteil_betroffener_shapes'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='entropy_statistik',
            field=models.JSONField(default=dict),
        ),
    ]
