# Generated by Django 5.2.7 on 2026-01-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzeInvoices', '0015_filter_entropy_statistik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='entropy_statistik',
        ),
        migrations.AddField(
            model_name='report',
            name='entropy_statistik',
            field=models.JSONField(default=dict),
        ),
    ]
