# Generated by Django 5.2.8 on 2026-02-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzeInvoices', '0016_remove_filter_entropy_statistik_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='most_violated_node',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='report',
            name='most_violated_path',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='report',
            name='most_violated_source_constraint_component',
            field=models.TextField(default=''),
        ),
    ]
