# Generated by Django 5.2.8 on 2026-02-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzeInvoices', '0017_report_most_violated_node_report_most_violated_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='focusNodeEntropy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='report',
            name='resultPathEntropy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='report',
            name='sourceConstraintComponentEntropy',
            field=models.FloatField(default=0.0),
        ),
    ]
