# Generated by Django 5.2.8 on 2026-02-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzeInvoices', '0019_remove_report_allpaths_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='allPaths',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='report',
            name='anteil_betroffener_shapes',
            field=models.TextField(default='0%'),
        ),
        migrations.AddField(
            model_name='report',
            name='anzahl_betroffener_shapes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='anzahl_betroffener_suppliers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='correlationData',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='report',
            name='datengraph',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='report',
            name='edi_content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='report',
            name='entropy_statistik',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='report',
            name='focusNodeEntropy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='report',
            name='focus_node_verteilung',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='report',
            name='graph',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='report',
            name='list_of_violations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='report',
            name='most_violated_node',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='report',
            name='most_violated_path',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='report',
            name='most_violated_source_constraint_component',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='report',
            name='resultPathEntropy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='report',
            name='result_path_verteilung',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='report',
            name='severity_verteilung',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='report',
            name='sourceConstraintComponentEntropy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='report',
            name='source_constraint_component_verteilung',
            field=models.JSONField(default=dict),
        ),
    ]
