# Generated by Django 5.2.8 on 2026-02-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzeInvoices', '0020_report_allpaths_report_anteil_betroffener_shapes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='anzahl_betroffener_suppliers',
            new_name='anzahl_betroffener_nodes',
        ),
        migrations.RemoveField(
            model_name='filter',
            name='anzahl_betroffener_suppliers',
        ),
        migrations.AddField(
            model_name='filter',
            name='anzahl_betroffener_nodes',
            field=models.IntegerField(default=0),
        ),
    ]
