# Generated by Django 5.2.8 on 2026-03-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzeInvoices', '0021_rename_anzahl_betroffener_suppliers_report_anzahl_betroffener_nodes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='datengraph',
            field=models.TextField(default=''),
        ),
    ]
